dist: xenial
language: python
sudo: false
python:
  - "3.6"
  - "3.7"
cache:
  pip: true
install:
  - pip install tox-travis codecov black==19.3b0
script:
  - tox
  - black --check .
env:
  matrix:
    - DJANGO="1.11"
    - DJANGO="2.0"
    - DJANGO="2.1"
    - DJANGO="master"
matrix:
  allow_failures:
    - python: "3.6"
      env: DJANGO="master"
  exclude:
    - python: "3.7"
      env: DJANGO="1.11"
after_success:
  - codecov
